### ISSUE TITLE
Support for MKLROOT as conan env var

### ISSUE THREAD

**Issue by romanc** [kylemacfarlan/conan-mkl#2]
Currently, `MKLROOT` must be set as a system/user-wide environment variable for this conan recipe to detect it. Conan has support [1] for environment variables, which can be defined in profiles or even at a package level. This gives much more fine-grained control to locate the desired version of MKL. These environment variables are accessed as `self.env["MKLROOT"]`. I think it would be desirable, if those would override `os.environ["MKLROOT"]`, if both are defined.

Do you think think, you could add this feature?

[1] https://docs.conan.io/en/latest/mastering/envvars.html

**Comment by kylemacfarlan** [comment]
I wasn't aware of  conan environment variables, but that is an elegant solution. I've made the change here https://github.com/kylemacfarlan/conan-mkl/commit/b6b9528f968d91456a6e38f54e4d705ecd33b655. 

Thanks for the suggestion!
